#!/sbin/openrc-run
# Copyright 1999-2019 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

name="Greenbone Security Assistant Daemon"
command="/usr/sbin/gsad"
command_args="${GSAD_OPTIONS} ${GSAD_LISTEN_ADDRESS} ${GSAD_LISTEN_PORT} ${GSAD_MANAGER_LISTEN_ADDRESS} ${GSAD_MANAGER_LISTEN_PORT} ${GSAD_GNUTLS_PRIORITIES}"
pidfile="/run/gsad.pid"
command_background="true"

depend() {
	after bootmisc
	need localmount net openvas-scanner gvmd
}
