#!/sbin/openrc-run
# Copyright 1999-2018 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

name="Greenbone Vulnerability Manager"
command=/usr/sbin/gvmd
command_args="${GVMD_OPTIONS} ${GVMD_PORT} ${GVMD_LISTEN_ADDRESS} ${GVMD_SCANNER_HOST} ${GVMD_GNUTLS_PRIORITIES}"
pidfile="/run/gvmd.pid"
command_background="true"

depend() {
	after bootmisc
	need localmount net openvas-scanner
}

start_pre() {
	checkpath --directory --mode 0775 --quiet /var/cache/openvas
}
